[package]
name = "arp-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
os_socketaddr = "0.2"
macaddr= "1"
tokio = {version = "1", features= ["full"]}